# Generated by Django 2.2.12 on 2020-07-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200709_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cim',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cim',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CIM',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
