# Generated by Django 2.2.12 on 2020-07-11 17:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_rating_review_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='RatingModel',
        ),
    ]
