# Generated by Django 2.2.12 on 2020-07-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200711_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
