# Generated by Django 2.2.12 on 2020-07-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingModel',
        ),
    ]
