# Generated by Django 2.2.12 on 2020-07-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delete_ratingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
