# Generated by Django 2.2.12 on 2020-07-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_Code',
            new_name='postal_code',
        ),
    ]
